// <auto-generated />
using AutoPharma.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoPharma.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220720203749_edit2")]
    partial class edit2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoPharma.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cityId")
                        .HasColumnType("int");

                    b.Property<string>("cityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("cityId");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Amman Street",
                            Phone = "1000",
                            cityId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Irbid Street",
                            Phone = "2000",
                            cityId = 3
                        });
                });

            modelBuilder.Entity("AutoPharma.Models.BranchMedicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<double>("OurPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("LocationId");

                    b.HasIndex("MedicineId");

                    b.ToTable("BranchMedicines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            Count = 73,
                            LocationId = 1,
                            MedicineId = 1,
                            OurPrice = 3.75
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 2,
                            Count = 120,
                            LocationId = 5,
                            MedicineId = 1,
                            OurPrice = 3.75
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 1,
                            Count = 22,
                            LocationId = 3,
                            MedicineId = 2,
                            OurPrice = 18.449999999999999
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 2,
                            Count = 17,
                            LocationId = 6,
                            MedicineId = 2,
                            OurPrice = 18.449999999999999
                        });
                });

            modelBuilder.Entity("AutoPharma.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Amman"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Zarqa"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Irbid"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Aqaba"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Maadaba"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Al-Balqaa"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mafraq"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Jerash"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ma'an"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Al-Tafila"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Al-Karak"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ajloun"
                        });
                });

            modelBuilder.Entity("AutoPharma.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Cabinet")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Shelf")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            Cabinet = "A",
                            Shelf = 1
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            Cabinet = "A",
                            Shelf = 2
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 1,
                            Cabinet = "A",
                            Shelf = 3
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 2,
                            Cabinet = "A",
                            Shelf = 1
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 2,
                            Cabinet = "A",
                            Shelf = 2
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 2,
                            Cabinet = "A",
                            Shelf = 3
                        });
                });

            modelBuilder.Entity("AutoPharma.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MOHPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dose = "250",
                            Information = "This medicine is used as a painkiller",
                            MOHPrice = 3.5,
                            Name = "Panadol"
                        },
                        new
                        {
                            Id = 2,
                            Dose = "500",
                            Information = "This medicine is used as a antibiotic",
                            MOHPrice = 17.649999999999999,
                            Name = "Penicillin "
                        });
                });

            modelBuilder.Entity("AutoPharma.Models.Branch", b =>
                {
                    b.HasOne("AutoPharma.Models.City", "City")
                        .WithMany("Branches")
                        .HasForeignKey("cityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("AutoPharma.Models.BranchMedicine", b =>
                {
                    b.HasOne("AutoPharma.Models.Branch", "Branch")
                        .WithMany("BranchMedicines")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoPharma.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoPharma.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Location");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("AutoPharma.Models.Branch", b =>
                {
                    b.Navigation("BranchMedicines");
                });

            modelBuilder.Entity("AutoPharma.Models.City", b =>
                {
                    b.Navigation("Branches");
                });
#pragma warning restore 612, 618
        }
    }
}
